
  name: Secrets
  on:
    workflow_dispatch:

  jobs:
    testing_secrets:
      name: Testing secrets
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4  # Actualiza a la versión que usa Node.js 20
        - name: My first secret
          run: echo ${{ secrets.USER1 }}
               echo ${{ secrets.PASS1 }}

  
