name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # Actualiza a la versión que usa Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # Actualiza a la versión que usa Node.js 20
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify secrets
      run: |
        if [ -z "$USER1" ]; then echo "USER1 secret not found"; else echo "USER1 secret loaded"; fi
        if [ -z "$PASS1" ]; then echo "PASS1 secret not found"; else echo "PASS1 secret loaded"; fi
      env:
        USER1: ${{ secrets.USER1 }}
        PASS1: ${{ secrets.PASS1 }}

    - name: Run your script
      env:
        USER1: ${{ secrets.USER1 }}
        PASS1: ${{ secrets.PASS1 }}
      run: |
        python Siapemad_dashboard.py
