name: Streamlit Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install streamlit
        pip install -r requirements.txt

    - name: Run Streamlit
      env:
        USER1: ${{ secrets.USER1 }}
        PASS1: ${{ secrets.PASS1 }}
      run: |
        streamlit run Siapemad_dashboard.py
